/*
------------------------------------
Question: What is the value of the first triangle number to have over five hundred divisors?

Tips: The sequence of triangle numbers is generated by adding the natural numbers. So the 7th
triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1,3,6,10,15,21,28,36,45,55,...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
we can see that 28 is the first triangle number to have over five divisors.
--------------------------------------
1)start
2)long int triangle_num = 0, counter = 0
3)int i = 8
4)if true,go to step 5
5)int j = 0
6)if j <= i, go to step 7, otherwise go to step 9
7)triangle_num += j
8)j++, go to step 6
9)int k = 1
10)if k <= triangle_num, go to step 11, otherwise go to step 16
11)if triangle_num % k == 0, go to step 12, otherwise go to step 15
12)if triangle_num == k*k, go to step 13, otherwise go to step 14
13)counter++, go to step 15
14)counter += 2, go to step 15
15)k++, go to step 10
16)if counter >= 500, go to step 17, otherwise go to step 19
17)print triangle_num
18)go to end(break)
19)triangle_num = 0
20)counter = 0
21)i++, go to step 4
22)end
---------------------------------------
*/

#include<stdio.h>
#include<math.h>

int main(){
    long int triangle_num = 0, counter = 0;
    
    int i = 8;
    while(1){
        for(int j = 1; j <= i; j++){
            triangle_num += j;
        }

        for(int k = 1; k <= sqrt(triangle_num); k++){
			if(triangle_num % k == 0){
				if(triangle_num  ==k * k){
					counter++;
				}else{
					counter += 2;
				}
			} 
		}
		printf("counter:%ld\n", counter);
        if(counter >= 500){
            printf("%ld", triangle_num);
            break;
        }
        triangle_num = 0;
        counter = 0;
        i++;
    }
}
